config/routes.rb
Pomodoro::Application.routes.draw do
  resources :activities do
    resources :spent_times
  end
  resources :spent_times
  resources :reports
  root :to => 'activities#new'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :description, :done

  has_many :spent_times, dependent: :destroy

  default_scope :order => 'updated_at DESC'

  after_initialize do |activity|
    activity.description ||= ""
    activity.done ||= false
  end

  def self.ordered_by_most_active
    # TODO: Optimize this method
    # TODO: Also check others
    self.all.sort do |a,b|
      b.activeness <=> a.activeness
    end
  end

  def self.executed_at(period)
    self.includes(:spent_times).all.select do |a|
      a.spent_times.any? do |s|
        period.cover?(s.updated_at)
      end
    end
  end

  def activeness
    last_execution_at ? last_execution_at : updated_at
  end

  def time_spent_at(period)
    times = spent_times_at(period)
    times.empty? ? 0 : times.map(&:time).reduce(:+)
  end

  def time_spent_per_day_at(period)
    period.map do |day|
      time_spent_at(day..day)
    end
  end

  def last_execution_at
    last_spent_time && last_spent_time.updated_at
  end

  private

  def spent_times_at(period)
    spent_times.select do |s|
      period.cover?(s.updated_at.to_date)
    end
  end

  def last_spent_time
    spent_times.last_updated
  end
end

app/models/activity_report.rb
require 'date/date_range'

class ActivityReport
  include ActiveModel::Validations
  include ActiveModel::Conversion

  attr_accessor :start_date, :end_date

  def persisted?
    false
  end

  def initialize(attrs = {})
    attrs ||= {}
    default_attrs.merge(attrs).each do |attr, value|
      send("#{attr}=", value) unless attr =~ /date/
    end
    assign_date_attributes(attrs)
    load_activities_with_time_spent
  end

  def each_with_times(&block)
    @activities.each do |a|
      yield(a, @report[a.id])
    end
  end

  def map_with_times(&block)
    @activities.map do |a|
      yield(a, @report[a.id])
    end
  end

  def period
    DateRange.new(start_date, end_date)
  end

  def total_spent_time
    TimeDecorator.new(
      map_with_times{|a,times| times.reduce(:+)}.reduce(:+)
    )
  end

  private

  def default_attrs
    {
      start_date: Date.today,
      end_date: Date.today
    }
  end

  def load_activities_with_time_spent
    @activities = Activity.executed_at(period)
    @report = @activities.each_with_object({}) do |a, r|
      r[a.id] = a.time_spent_per_day_at(period).map do |time|
        TimeDecorator.new(time)
      end
    end
  end

  def assign_date_attributes(attrs)
    default_attrs.each do |k,v|
      send("#{k}=",v)
    end
    [:start_date, :end_date].each do |attr|
      send("#{attr}=", Date.new(
        attrs["#{attr}(1i)"].to_i,
        attrs["#{attr}(2i)"].to_i,
        attrs["#{attr}(3i)"].to_i
      )) unless attrs["#{attr}(1i)"].nil?
    end
  end
end

app/models/report.rb
class Report
  include ActiveModel::Validations
  include ActiveModel::Conversion

  attr_accessor :start_date, :end_date

  def persisted?
    false
  end

  def initialize(attrs = {})
    attrs ||= {}
    default_attrs.merge(attrs).each do |attr, value|
      send("#{attr}=", value) unless attr =~ /date/
    end
    assign_date_attributes(attrs)
    load_activities_with_time_spent
  end

  def each_with_times(&block)
    @activities.each do |a|
      yield(a, @report[a.id])
    end
  end

  private

  def default_attrs
    {
      start_date: Date.today,
      end_date: Date.today + 1.day
    }
  end

  def load_activities_with_time_spent
    @activities = Activity.executed_between(start_date, end_date)
    @report = @activities.each_with_object({}) do |a, r|
      r[a.id] = a.time_spent_per_day_between(start_date, end_date)
    end
  end

  def assign_date_attributes(attrs)
    default_attrs.each do |k,v|
      send("#{k}=",v)
    end
    [:start_date, :end_date].each do |attr|
      send("#{attr}=", Date.new(
        attrs["#{attr}(1i)"].to_i,
        attrs["#{attr}(2i)"].to_i,
        attrs["#{attr}(3i)"].to_i
      )) unless attrs["#{attr}(1i)"].nil?
    end
  end
end

app/models/spent_time.rb
class SpentTime < ActiveRecord::Base
  attr_accessible :activity_id, :time

  belongs_to :activity

  validates :activity, presence: true

  scope :updated_today, lambda {
    where('updated_at > ?', Date.today)
  }

  def self.last_updated
    order('updated_at DESC').first
  end

  after_initialize do |st|
    st.time ||= 0
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  respond_to :html, :json

  def index
    respond_with(@activities = Activity.all)
  end

  def new
    @activity = Activity.new
    @activities = Activity.ordered_by_most_active
    @spent_times = SpentTime.updated_today
  end

  def create
    activity = Activity.new(params[:activity])
    activity.save
    respond_with activity
  end

  def update
    activity = Activity.find(params[:id])
    activity.update_attributes(params[:activity])
    respond_with activity
  end

  def destroy
    activity = Activity.find(params[:id])
    activity.destroy
    respond_with(activity)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  respond_to :html

  def index
    @report = ActivityReport.new(params[:activity_report])
  end
end

app/controllers/spent_times_controller.rb
class SpentTimesController < ApplicationController
  respond_to :html, :json

  before_filter :load_activity, except: [:destroy]

  def index
    respond_with(spent_times)
  end

  def create
    spent_time = SpentTime.new(params[:spent_time])
    spent_time.save
    respond_with @activity, spent_time
  end

  def destroy
    spent_time = SpentTime.find(params[:id])
    spent_time.destroy
    respond_with(spent_time)
  end

  private

  def load_activity
    @activity = Activity.find(params[:activity_id]) if params[:activity_id]
  end

  def spent_times
    @activity ? @activity.spent_times : SpentTime.updated_today
  end
end

app/views/activities/new.html.haml
%section
  %p
    Today you've spent:
    %span#total-spent-time
    (#{link_to 'see more', reports_path, target: '_blank'})

%section#timer-area
  %p#commands
    %a#pomodoro{ href: '#' } Pomodoro
    |
    %a#long-break{ href: '#' } Long Break
    |
    %a#short-break{ href: '#' } Short Break
  %p
    %span#timer
    %span#notification

%section#activity-area
  %form#new-activity
    %p
      %label{ for: "activity-description", style: "display: none" }
        Description
      %input#activity-description{ type: 'text', size: '30' }
    %p
      %input{ type: 'submit', value: 'Add' }

  %ol#activities

- content_for :javascript do
  :javascript
    $(function() {
      window.router = new Pomodoro.Routers.Activities({
        activities: #{@activities.to_json.html_safe},
        spentTimes: #{@spent_times.to_json.html_safe}
      });
      Backbone.history.start();
    });

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Pomodoro
    = stylesheet_link_tag    "application", :media => "all"
    = csrf_meta_tags
    = javascript_include_tag "application"
  %body
    = yield
    = yield :javascript

app/views/reports/index.html.haml
= form_for @report, url: reports_path, method: :get do |f|
  %p
    = f.label :start_date
    = f.date_select :start_date
  %p
    = f.label :end_date
    = f.date_select :end_date
  %p
    = f.submit 'Submit'

%table
  %thead
    %tr
      %th
        Activity (hh:mm:ss)
      - @report.period.each do |date|
        %th
          = date.strftime('%a')
      %th
        Total
  %tbody
    - @report.each_with_times do |activity, times|
      %tr
        %td
          = activity.description
        - times.each do |time|
          %td
            = time.to_hh_mm_ss
        %td
          = times.reduce(:+).to_hh_mm_ss
  %tfoot
    %tr
      %td
      - @report.period.each do |date|
        %td
      %td
        = @report.total_spent_time.to_hh_mm_ss